[2023-10-11T19:27:43.256+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wikipedia_etl.trusted scheduled__2023-10-06T00:00:00+00:00 [queued]>
[2023-10-11T19:27:43.276+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wikipedia_etl.trusted scheduled__2023-10-06T00:00:00+00:00 [queued]>
[2023-10-11T19:27:43.276+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 3
[2023-10-11T19:27:43.318+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): trusted> on 2023-10-06 00:00:00+00:00
[2023-10-11T19:27:43.328+0000] {standard_task_runner.py:57} INFO - Started process 586 to run task
[2023-10-11T19:27:43.332+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'wikipedia_etl', 'trusted', 'scheduled__2023-10-06T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/wikipedia_etl.py', '--cfg-path', '/tmp/tmpw0az397y']
[2023-10-11T19:27:43.336+0000] {standard_task_runner.py:85} INFO - Job 20: Subtask trusted
[2023-10-11T19:27:43.427+0000] {task_command.py:415} INFO - Running <TaskInstance: wikipedia_etl.trusted scheduled__2023-10-06T00:00:00+00:00 [running]> on host f711e14c143e
[2023-10-11T19:27:43.532+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='wikipedia_etl' AIRFLOW_CTX_TASK_ID='trusted' AIRFLOW_CTX_EXECUTION_DATE='2023-10-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-06T00:00:00+00:00'
[2023-10-11T19:28:38.823+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to None. Terminating instance.
[2023-10-11T19:28:38.826+0000] {process_utils.py:131} INFO - Sending 15 to group 586. PIDs of all processes in the group: [605, 586]
[2023-10-11T19:28:38.826+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 586
[2023-10-11T19:28:38.827+0000] {taskinstance.py:1630} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-10-11T19:28:38.835+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/wikipedia_etl.py", line 133, in trusted
    sc = SparkContext(conf=conf)
  File "/home/airflow/.local/lib/python3.8/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.8/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "/home/airflow/.local/lib/python3.8/site-packages/pyspark/java_gateway.py", line 104, in launch_gateway
    time.sleep(0.1)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1632, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-10-11T19:28:38.838+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=wikipedia_etl, task_id=trusted, execution_date=20231006T000000, start_date=20231011T192743, end_date=20231011T192838
[2023-10-11T19:28:38.850+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 20 for task trusted ((psycopg2.errors.ForeignKeyViolation) insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(wikipedia_etl, trusted, scheduled__2023-10-06T00:00:00+00:00, -1) is not present in table "task_instance".

[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (%(task_id)s, %(dag_id)s, %(run_id)s, %(map_index)s, %(start_date)s, %(end_date)s, %(duration)s) RETURNING task_fail.id]
[parameters: {'task_id': 'trusted', 'dag_id': 'wikipedia_etl', 'run_id': 'scheduled__2023-10-06T00:00:00+00:00', 'map_index': -1, 'start_date': datetime.datetime(2023, 10, 11, 19, 27, 43, 257097, tzinfo=Timezone('UTC')), 'end_date': datetime.datetime(2023, 10, 11, 19, 28, 38, 838276, tzinfo=Timezone('UTC')), 'duration': 55}]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 586)
[2023-10-11T19:28:38.879+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=586, status='terminated', exitcode=1, started='19:27:42') (586) terminated with exit code 1
[2023-10-11T19:28:39.012+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=605, status='terminated', started='19:27:42') (605) terminated with exit code None
[2023-10-11T19:33:45.458+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wikipedia_etl.trusted scheduled__2023-10-06T00:00:00+00:00 [queued]>
[2023-10-11T19:33:45.465+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wikipedia_etl.trusted scheduled__2023-10-06T00:00:00+00:00 [queued]>
[2023-10-11T19:33:45.465+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 3
[2023-10-11T19:33:45.476+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): trusted> on 2023-10-06 00:00:00+00:00
[2023-10-11T19:33:45.482+0000] {standard_task_runner.py:57} INFO - Started process 2177 to run task
[2023-10-11T19:33:45.485+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'wikipedia_etl', 'trusted', 'scheduled__2023-10-06T00:00:00+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/wikipedia_etl.py', '--cfg-path', '/tmp/tmp1g18rk7l']
[2023-10-11T19:33:45.488+0000] {standard_task_runner.py:85} INFO - Job 34: Subtask trusted
[2023-10-11T19:33:45.537+0000] {task_command.py:415} INFO - Running <TaskInstance: wikipedia_etl.trusted scheduled__2023-10-06T00:00:00+00:00 [running]> on host f711e14c143e
[2023-10-11T19:33:45.603+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='wikipedia_etl' AIRFLOW_CTX_TASK_ID='trusted' AIRFLOW_CTX_EXECUTION_DATE='2023-10-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-06T00:00:00+00:00'
[2023-10-11T19:34:12.156+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-10-11T19:34:12.166+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=wikipedia_etl, task_id=trusted, execution_date=20231006T000000, start_date=20231011T193345, end_date=20231011T193412
[2023-10-11T19:34:12.208+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-11T19:34:12.222+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-11T19:49:19.411+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wikipedia_etl.trusted scheduled__2023-10-06T00:00:00+00:00 [queued]>
[2023-10-11T19:49:19.419+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wikipedia_etl.trusted scheduled__2023-10-06T00:00:00+00:00 [queued]>
[2023-10-11T19:49:19.419+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 3
[2023-10-11T19:49:19.430+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): trusted> on 2023-10-06 00:00:00+00:00
[2023-10-11T19:49:19.434+0000] {standard_task_runner.py:57} INFO - Started process 4885 to run task
[2023-10-11T19:49:19.437+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'wikipedia_etl', 'trusted', 'scheduled__2023-10-06T00:00:00+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/wikipedia_etl.py', '--cfg-path', '/tmp/tmp9pkauykf']
[2023-10-11T19:49:19.439+0000] {standard_task_runner.py:85} INFO - Job 54: Subtask trusted
[2023-10-11T19:49:19.475+0000] {task_command.py:415} INFO - Running <TaskInstance: wikipedia_etl.trusted scheduled__2023-10-06T00:00:00+00:00 [running]> on host f711e14c143e
[2023-10-11T19:49:19.533+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='wikipedia_etl' AIRFLOW_CTX_TASK_ID='trusted' AIRFLOW_CTX_EXECUTION_DATE='2023-10-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-06T00:00:00+00:00'
[2023-10-11T19:49:49.461+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-10-11T19:49:49.472+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=wikipedia_etl, task_id=trusted, execution_date=20231006T000000, start_date=20231011T194919, end_date=20231011T194949
[2023-10-11T19:49:49.501+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-11T19:49:49.514+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-13T17:20:42.925+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wikipedia_etl.trusted scheduled__2023-10-06T00:00:00+00:00 [queued]>
[2023-10-13T17:20:42.932+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wikipedia_etl.trusted scheduled__2023-10-06T00:00:00+00:00 [queued]>
[2023-10-13T17:20:42.932+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 3
[2023-10-13T17:20:42.941+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): trusted> on 2023-10-06 00:00:00+00:00
[2023-10-13T17:20:42.948+0000] {standard_task_runner.py:57} INFO - Started process 1341 to run task
[2023-10-13T17:20:42.951+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'wikipedia_etl', 'trusted', 'scheduled__2023-10-06T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/wikipedia_etl.py', '--cfg-path', '/tmp/tmpr_axb3ma']
[2023-10-13T17:20:42.953+0000] {standard_task_runner.py:85} INFO - Job 14: Subtask trusted
[2023-10-13T17:20:42.990+0000] {task_command.py:415} INFO - Running <TaskInstance: wikipedia_etl.trusted scheduled__2023-10-06T00:00:00+00:00 [running]> on host feba906f3341
[2023-10-13T17:20:43.051+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='wikipedia_etl' AIRFLOW_CTX_TASK_ID='trusted' AIRFLOW_CTX_EXECUTION_DATE='2023-10-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-06T00:00:00+00:00'
[2023-10-13T17:21:22.411+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-10-13T17:21:22.421+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=wikipedia_etl, task_id=trusted, execution_date=20231006T000000, start_date=20231013T172042, end_date=20231013T172122
[2023-10-13T17:21:22.456+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-13T17:21:22.468+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-16T11:28:08.550+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wikipedia_etl.trusted scheduled__2023-10-06T00:00:00+00:00 [queued]>
[2023-10-16T11:28:08.557+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wikipedia_etl.trusted scheduled__2023-10-06T00:00:00+00:00 [queued]>
[2023-10-16T11:28:08.558+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 3
[2023-10-16T11:28:08.568+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): trusted> on 2023-10-06 00:00:00+00:00
[2023-10-16T11:28:08.574+0000] {standard_task_runner.py:57} INFO - Started process 1323 to run task
[2023-10-16T11:28:08.577+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'wikipedia_etl', 'trusted', 'scheduled__2023-10-06T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/wikipedia_etl.py', '--cfg-path', '/tmp/tmpgb5xblzj']
[2023-10-16T11:28:08.579+0000] {standard_task_runner.py:85} INFO - Job 14: Subtask trusted
[2023-10-16T11:28:08.619+0000] {task_command.py:415} INFO - Running <TaskInstance: wikipedia_etl.trusted scheduled__2023-10-06T00:00:00+00:00 [running]> on host ab44499fca46
[2023-10-16T11:28:08.687+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='wikipedia_etl' AIRFLOW_CTX_TASK_ID='trusted' AIRFLOW_CTX_EXECUTION_DATE='2023-10-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-06T00:00:00+00:00'
[2023-10-16T11:28:43.063+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-10-16T11:28:43.074+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=wikipedia_etl, task_id=trusted, execution_date=20231006T000000, start_date=20231016T112808, end_date=20231016T112843
[2023-10-16T11:28:43.111+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-16T11:28:43.124+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
