[2023-10-11T19:27:21.789+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wikipedia_etl.trusted scheduled__2023-10-01T00:00:00+00:00 [queued]>
[2023-10-11T19:27:21.800+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wikipedia_etl.trusted scheduled__2023-10-01T00:00:00+00:00 [queued]>
[2023-10-11T19:27:21.801+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 3
[2023-10-11T19:27:21.814+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): trusted> on 2023-10-01 00:00:00+00:00
[2023-10-11T19:27:21.836+0000] {standard_task_runner.py:57} INFO - Started process 232 to run task
[2023-10-11T19:27:21.840+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'wikipedia_etl', 'trusted', 'scheduled__2023-10-01T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/wikipedia_etl.py', '--cfg-path', '/tmp/tmp81wvhoy1']
[2023-10-11T19:27:21.843+0000] {standard_task_runner.py:85} INFO - Job 16: Subtask trusted
[2023-10-11T19:27:21.932+0000] {task_command.py:415} INFO - Running <TaskInstance: wikipedia_etl.trusted scheduled__2023-10-01T00:00:00+00:00 [running]> on host f711e14c143e
[2023-10-11T19:27:22.055+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='wikipedia_etl' AIRFLOW_CTX_TASK_ID='trusted' AIRFLOW_CTX_EXECUTION_DATE='2023-10-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-01T00:00:00+00:00'
[2023-10-11T19:28:37.632+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to None. Terminating instance.
[2023-10-11T19:28:37.634+0000] {process_utils.py:131} INFO - Sending 15 to group 232. PIDs of all processes in the group: [267, 232]
[2023-10-11T19:28:37.634+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 232
[2023-10-11T19:28:37.634+0000] {taskinstance.py:1630} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-10-11T19:28:37.635+0000] {clientserver.py:538} INFO - Error while receiving.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1632, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-10-11T19:28:37.637+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-10-11T19:28:37.637+0000] {java_gateway.py:1055} ERROR - Exception while sending command.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1632, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/airflow/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 539, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending or receiving
[2023-10-11T19:28:37.639+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-10-11T19:28:37.639+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/wikipedia_etl.py", line 173, in trusted
    df.write.partitionBy("processing_date").parquet(
  File "/home/airflow/.local/lib/python3.8/site-packages/pyspark/sql/readwriter.py", line 1721, in parquet
    self._jwrite.parquet(path)
  File "/home/airflow/.local/lib/python3.8/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
  File "/home/airflow/.local/lib/python3.8/site-packages/pyspark/errors/exceptions/captured.py", line 179, in deco
    return f(*a, **kw)
  File "/home/airflow/.local/lib/python3.8/site-packages/py4j/protocol.py", line 334, in get_return_value
    raise Py4JError(
py4j.protocol.Py4JError: An error occurred while calling o58.parquet
[2023-10-11T19:28:37.650+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=wikipedia_etl, task_id=trusted, execution_date=20231001T000000, start_date=20231011T192721, end_date=20231011T192837
[2023-10-11T19:28:37.664+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 16 for task trusted ((psycopg2.errors.ForeignKeyViolation) insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(wikipedia_etl, trusted, scheduled__2023-10-01T00:00:00+00:00, -1) is not present in table "task_instance".

[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (%(task_id)s, %(dag_id)s, %(run_id)s, %(map_index)s, %(start_date)s, %(end_date)s, %(duration)s) RETURNING task_fail.id]
[parameters: {'task_id': 'trusted', 'dag_id': 'wikipedia_etl', 'run_id': 'scheduled__2023-10-01T00:00:00+00:00', 'map_index': -1, 'start_date': datetime.datetime(2023, 10, 11, 19, 27, 21, 790267, tzinfo=Timezone('UTC')), 'end_date': datetime.datetime(2023, 10, 11, 19, 28, 37, 649518, tzinfo=Timezone('UTC')), 'duration': 75}]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 232)
[2023-10-11T19:28:38.089+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=267, status='terminated', started='19:27:21') (267) terminated with exit code None
[2023-10-11T19:28:38.089+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=232, status='terminated', exitcode=1, started='19:27:21') (232) terminated with exit code 1
[2023-10-11T19:31:37.806+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wikipedia_etl.trusted scheduled__2023-10-01T00:00:00+00:00 [queued]>
[2023-10-11T19:31:37.813+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wikipedia_etl.trusted scheduled__2023-10-01T00:00:00+00:00 [queued]>
[2023-10-11T19:31:37.813+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 3
[2023-10-11T19:31:37.824+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): trusted> on 2023-10-01 00:00:00+00:00
[2023-10-11T19:31:37.829+0000] {standard_task_runner.py:57} INFO - Started process 1004 to run task
[2023-10-11T19:31:37.832+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'wikipedia_etl', 'trusted', 'scheduled__2023-10-01T00:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/wikipedia_etl.py', '--cfg-path', '/tmp/tmp07g80cmp']
[2023-10-11T19:31:37.834+0000] {standard_task_runner.py:85} INFO - Job 24: Subtask trusted
[2023-10-11T19:31:37.875+0000] {task_command.py:415} INFO - Running <TaskInstance: wikipedia_etl.trusted scheduled__2023-10-01T00:00:00+00:00 [running]> on host f711e14c143e
[2023-10-11T19:31:37.945+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='wikipedia_etl' AIRFLOW_CTX_TASK_ID='trusted' AIRFLOW_CTX_EXECUTION_DATE='2023-10-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-01T00:00:00+00:00'
[2023-10-11T19:31:52.914+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-10-11T19:31:52.927+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=wikipedia_etl, task_id=trusted, execution_date=20231001T000000, start_date=20231011T193137, end_date=20231011T193152
[2023-10-11T19:31:52.948+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-11T19:31:52.960+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-11T19:46:05.425+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wikipedia_etl.trusted scheduled__2023-10-01T00:00:00+00:00 [queued]>
[2023-10-11T19:46:05.432+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wikipedia_etl.trusted scheduled__2023-10-01T00:00:00+00:00 [queued]>
[2023-10-11T19:46:05.432+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 3
[2023-10-11T19:46:05.443+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): trusted> on 2023-10-01 00:00:00+00:00
[2023-10-11T19:46:05.447+0000] {standard_task_runner.py:57} INFO - Started process 3574 to run task
[2023-10-11T19:46:05.449+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'wikipedia_etl', 'trusted', 'scheduled__2023-10-01T00:00:00+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/wikipedia_etl.py', '--cfg-path', '/tmp/tmp4z9eiz8n']
[2023-10-11T19:46:05.451+0000] {standard_task_runner.py:85} INFO - Job 44: Subtask trusted
[2023-10-11T19:46:05.490+0000] {task_command.py:415} INFO - Running <TaskInstance: wikipedia_etl.trusted scheduled__2023-10-01T00:00:00+00:00 [running]> on host f711e14c143e
[2023-10-11T19:46:05.544+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='wikipedia_etl' AIRFLOW_CTX_TASK_ID='trusted' AIRFLOW_CTX_EXECUTION_DATE='2023-10-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-01T00:00:00+00:00'
[2023-10-11T19:46:37.035+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-10-11T19:46:37.045+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=wikipedia_etl, task_id=trusted, execution_date=20231001T000000, start_date=20231011T194605, end_date=20231011T194637
[2023-10-11T19:46:37.073+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-11T19:46:37.087+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-13T17:14:22.161+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wikipedia_etl.trusted scheduled__2023-10-01T00:00:00+00:00 [queued]>
[2023-10-13T17:14:22.170+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wikipedia_etl.trusted scheduled__2023-10-01T00:00:00+00:00 [queued]>
[2023-10-13T17:14:22.170+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 3
[2023-10-13T17:14:22.184+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): trusted> on 2023-10-01 00:00:00+00:00
[2023-10-13T17:14:22.190+0000] {standard_task_runner.py:57} INFO - Started process 85 to run task
[2023-10-13T17:14:22.194+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'wikipedia_etl', 'trusted', 'scheduled__2023-10-01T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/wikipedia_etl.py', '--cfg-path', '/tmp/tmp275duyz4']
[2023-10-13T17:14:22.197+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask trusted
[2023-10-13T17:14:22.249+0000] {task_command.py:415} INFO - Running <TaskInstance: wikipedia_etl.trusted scheduled__2023-10-01T00:00:00+00:00 [running]> on host feba906f3341
[2023-10-13T17:14:22.324+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='wikipedia_etl' AIRFLOW_CTX_TASK_ID='trusted' AIRFLOW_CTX_EXECUTION_DATE='2023-10-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-01T00:00:00+00:00'
[2023-10-13T17:17:07.499+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-10-13T17:17:07.514+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=wikipedia_etl, task_id=trusted, execution_date=20231001T000000, start_date=20231013T171422, end_date=20231013T171707
[2023-10-13T17:17:07.565+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-13T17:17:07.592+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-16T11:23:44.287+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wikipedia_etl.trusted scheduled__2023-10-01T00:00:00+00:00 [queued]>
[2023-10-16T11:23:44.297+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wikipedia_etl.trusted scheduled__2023-10-01T00:00:00+00:00 [queued]>
[2023-10-16T11:23:44.297+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 3
[2023-10-16T11:23:44.314+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): trusted> on 2023-10-01 00:00:00+00:00
[2023-10-16T11:23:44.324+0000] {standard_task_runner.py:57} INFO - Started process 85 to run task
[2023-10-16T11:23:44.328+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'wikipedia_etl', 'trusted', 'scheduled__2023-10-01T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/wikipedia_etl.py', '--cfg-path', '/tmp/tmp23j073p_']
[2023-10-16T11:23:44.331+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask trusted
[2023-10-16T11:23:44.395+0000] {task_command.py:415} INFO - Running <TaskInstance: wikipedia_etl.trusted scheduled__2023-10-01T00:00:00+00:00 [running]> on host ab44499fca46
[2023-10-16T11:23:44.490+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='wikipedia_etl' AIRFLOW_CTX_TASK_ID='trusted' AIRFLOW_CTX_EXECUTION_DATE='2023-10-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-01T00:00:00+00:00'
[2023-10-16T11:24:59.513+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-10-16T11:24:59.527+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=wikipedia_etl, task_id=trusted, execution_date=20231001T000000, start_date=20231016T112344, end_date=20231016T112459
[2023-10-16T11:24:59.584+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-16T11:24:59.606+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-16T19:06:40.780+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wikipedia_etl.trusted scheduled__2023-10-01T00:00:00+00:00 [queued]>
[2023-10-16T19:06:40.793+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wikipedia_etl.trusted scheduled__2023-10-01T00:00:00+00:00 [queued]>
[2023-10-16T19:06:40.794+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 3
[2023-10-16T19:06:40.808+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): trusted> on 2023-10-01 00:00:00+00:00
[2023-10-16T19:06:40.814+0000] {standard_task_runner.py:57} INFO - Started process 85 to run task
[2023-10-16T19:06:40.818+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'wikipedia_etl', 'trusted', 'scheduled__2023-10-01T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/wikipedia_etl.py', '--cfg-path', '/tmp/tmptup4iu21']
[2023-10-16T19:06:40.822+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask trusted
[2023-10-16T19:06:40.875+0000] {task_command.py:415} INFO - Running <TaskInstance: wikipedia_etl.trusted scheduled__2023-10-01T00:00:00+00:00 [running]> on host 3522330161cc
[2023-10-16T19:06:40.957+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='wikipedia_etl' AIRFLOW_CTX_TASK_ID='trusted' AIRFLOW_CTX_EXECUTION_DATE='2023-10-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-01T00:00:00+00:00'
[2023-10-16T19:07:56.266+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-10-16T19:07:56.283+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=wikipedia_etl, task_id=trusted, execution_date=20231001T000000, start_date=20231016T190640, end_date=20231016T190756
[2023-10-16T19:07:56.352+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-16T19:07:56.375+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
